In [3]:
from video_tools import load_video
import numpy as np

In [39]:
def Omega(M, frame_size=(100,100)):
    """
    Valor de la norma Omega de la matriz D. los valores de frame_size se usan
    para calcular los indices g que necesita la norma
    """
    video = M.reshape((frame_size[0], frame_size[1], M.shape[1]))
    
    z = np.zeros(M.shape[1])
    for i in range(1, frame_size[0]-1): 
        for j in range(1, frame_size[1]-1): 
            window = video[i-1:i+2, j-1:j+2, :]
            vec_window = window.reshape(9, window.shape[2])
            z+= np.max(vec_window, axis=0)
    
    omega = np.sum(z)
    
    return z

In [40]:
D = load_video('test.avi')

In [41]:
Omega(D)

array([ 476533.,  479183.,  481597.,  481583.,  481605.,  481599.,
        481618.,  481616.,  481662.,  481688.,  481721.,  481754.,
        481521.,  481521.,  481521.,  481521.,  481377.,  481377.,
        481377.,  481377.,  481377.,  481338.,  481297.,  481297.,
        481485.,  481485.,  481485.,  481485.,  481485.,  481485.,
        481485.,  481485.,  481485.,  481415.,  481353.,  481259.,
        481521.,  481482.,  481441.,  481441.,  481441.,  481441.,
        481441.,  481441.,  481441.,  481441.,  481441.,  481441.,
        481485.,  481415.,  481353.,  481259.,  481225.,  481172.,
        481140.,  481140.,  481140.,  481140.,  481140.,  481140.,
        481521.,  481521.,  481521.,  481521.,  481377.,  481377.,
        481377.,  481377.,  481377.,  481338.,  481297.,  481297.,
        481485.,  481485.,  481485.,  481485.,  481485.,  481485.,
        481485.,  481485.,  481485.,  481415.,  481353.,  481259.,
        481521.,  481482.,  481441.,  481441.,  481441.,  4789

In [5]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
A = np.arange(25*5).reshape((25,5))

In [15]:
B = A.reshape((5,5,5))

In [21]:
B[:,:,0]

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120]])

In [34]:
z = np.zeros(5)
for i in range(1,4):
    for j in range(1,4):
        print(i,j)
        print(B[i-1:i+2, j-1:j+2, :])
        print(B[i-1:i+2, j-1:j+2, :].reshape((9,5)))
        print(np.max(B[i-1:i+2, j-1:j+2, :].reshape((9,5)), axis=0))
        
        z += np.max(B[i-1:i+2, j-1:j+2, :].reshape((9,5)), axis=0)

1 1
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]]
[60 61 62 63 64]
1 2
[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]
[65 66 67 68 69]
1 3
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46

In [36]:
B[0-1:0+2, 0-1:0+2, :].shape[2]

5